config/routes.rb
Treasure::Application.routes.draw do
  root :to => 'restaurants#index'

  resources :restaurants, :only => [:index, :show, :create, :new]

  get 'restaurants/random' => 'restaurantss#random', :as => :random_restaurant
end

app/models/restaurant.rb
class Restaurant
  # attr_accessible :address, :name, :url
  attr_reader :address, :name, :url

  def initialize(hash = {})
  	@name = hash[:name]
  	@address = hash[:address]
  	@url = hash[:url]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
	def index
		@restaurants = REDIS.hgetall('restaurants').values.map{|r| Marshal::load(r)}.sample(3)
	end

	def create
		restaurant = Restaurant.new(params[:restaurant])
    #this will be a problem when we start deleting restaurants...I'll find a better
    #way to do it
		next_index = (REDIS.hlen 'restaurants') + 1
    REDIS.hmset 'restaurants', "restaurant_#{next_index}", Marshal::dump(restaurant)
    render 'new'
	end

   def new
    @restaurant = Restaurant.new
  end

	def show
		id = params[:id]
		@restaurant = Marshal::load(REDIS.hmget('restaurants', "restaurant_#{id}").first)
	end

	def random
		random_index = rand(REDIS.hlen 'restaurants') + 1
		restaurant = Marshal::load(REDIS.hmget('restaurants', "restaurant_#{random_index}").first)

		respond_to do |format|
			format.json { render :json => restaurant}
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Treasure
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = yield

app/views/restaurants/index.html.haml
#overlay
.treasure1
  .text
    = @restaurants[0].name
    %br
    = @restaurants[0].address
.treasure2
  .text
    = @restaurants[1].name
    %br
    = @restaurants[1].address
.treasure3
  .text
    = @restaurants[2].name
    %br
    = @restaurants[2].address

app/views/restaurants/new.html.erb
<form action="<%= restaurants_url %>" method="post">
  <label for="restaurant_name">name</label>
  <input type="text" name="restaurant[name]" id="restaurant_name">

  <label for="restaurant_address">address</label>
  <input type="text" name="restaurant[address]" id="restaurant_address">

  <label for="restaurant_url">url</label>
  <input type="text" name="restaurant[url]" id="restaurant_url">

  <input type="submit" value="create">
</form>